### ISSUE TITLE
Fetching a related resource

### ISSUE THREAD

**Issue by khornberg** [vladmunteanu/starlette-jsonapi#7]
I didn't see an ability to fetch a [related resource](https://jsonapi.org/format/#fetching-resources)

In the spec's example I'm trying to do
```
GET /articles/1/author HTTP/1.1
Accept: application/vnd.api+json
```

I tried to hack in a way on the `BaseResource` to add the route automatically
I could not find a way to look at the `schema` and determine the fields that were of `JSONAPIRelationship`. Maybe I am missing something. Is this possible?

**Comment by vladmunteanu** [comment]
The examples directory should have a working setup for include. Have you looked at the postman file?
If not, take a look at the Readme inside examples and then try to run one of those.

The spec actually talks about fetching related resources via the "include" query parameter.

So if you look at examples/sample-plain and fire up the service, you should then be able to get the related resource in the same body from `/api/users/?include=organization`.

I don't think that /resource/<id>/related-resource is enforced by the spec tho. It seemed to me like `included` or the relationship related url would be the way to solve this.

**Comment by vladmunteanu** [comment]
To automatically add another route to the related resource based on a relationship, we would need to be able to link the related resource with the relationship somehow.

Late night idea:
I think the easiest way would be to change how JSONAPIRelationship is defined by specifying the related resource instead of the schema (specifying schema would be optional since we would be able to deduce it from the resource). Then, in `register_routes`, we would go from schema to related resources , mounting the related urls.
Probably some light meta programming needed to register resource names so that we don't encourage circular dependencies.

**Comment by vladmunteanu** [comment]
An attempt to address this can be seen at #11

**Comment by vladmunteanu** [comment]
Preparing final touches for #11. Thought I would update this issue with an overview:
- to support fetching related data, one will need to implement `get_related`, calling `serialize_related` to serialize the data.
- to expose related links when rendering a relationship, one will need to set `related_resource`, `related_route` and `related_route_kwargs` when creating a `JSONAPIRelationship` object.

**Comment by khornberg** [comment]
Thank you much for considering and adding this functionality
